
spring-sidecar-v1:
  image: spring-sidecar-ap
  environment:
    - A8_REGISTRY_URL=http://registry:8080
    - A8_SERVICE=spring:version=v1
    - A8_REGISTER=true
    - A8_ENDPOINT_PORT=9005
  external_links:
    - registry